CREATE TABLE public.booking (
                                id bigint NOT NULL,
                                booking_date date,
                                mail_send_date date,
                                title character varying(255),
                                member_id bigint
);


ALTER TABLE public.booking OWNER TO ocr_admin;

--
-- TOC entry 209 (class 1259 OID 21769)
-- Name: booking_id_seq; Type: SEQUENCE; Schema: public; Owner: ocr_admin
--

ALTER TABLE public.booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 2828 (class 2606 OID 21775)
-- Name: booking booking_pkey; Type: CONSTRAINT; Schema: public; Owner: ocr_admin
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (id);

--
-- TOC entry 2830 (class 2606 OID 21776)
-- Name: booking fkr200vemsolh30s8wvtold760v; Type: FK CONSTRAINT; Schema: public; Owner: ocr_admin
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkr200vemsolh30s8wvtold760v FOREIGN KEY (member_id) REFERENCES public.member(id);
