--
-- PostgreSQL database dump
--

-- Dumped from database version 12.5 (Ubuntu 12.5-1.pgdg20.04+1)
-- Dumped by pg_dump version 13.1 (Ubuntu 13.1-1.pgdg20.04+1)

-- Started on 2021-02-09 10:28:45 CET

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2962 (class 1262 OID 20811)
-- Name: ocr_loan; Type: DATABASE; Schema: -; Owner: ocr_admin
--

CREATE DATABASE testloan WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.UTF-8';


ALTER DATABASE testloan OWNER TO ocr_admin;

\connect testloan

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 21771)
-- Name: booking; Type: TABLE; Schema: public; Owner: ocr_admin
--

CREATE TABLE public.booking (
                                id bigint NOT NULL,
                                booking_date date,
                                mail_send_date date,
                                title character varying(255),
                                member_id bigint
);


ALTER TABLE public.booking OWNER TO ocr_admin;

--
-- TOC entry 209 (class 1259 OID 21769)
-- Name: booking_id_seq; Type: SEQUENCE; Schema: public; Owner: ocr_admin
--

ALTER TABLE public.booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 21636)
-- Name: loan; Type: TABLE; Schema: public; Owner: ocr_admin
--

CREATE TABLE public.loan (
                             id bigint NOT NULL,
                             book_back_date date,
                             label character varying(255),
                             refresh_ending_counter integer NOT NULL,
                             starting_date date,
                             title character varying(255),
                             member_id bigint
);


ALTER TABLE public.loan OWNER TO ocr_admin;

--
-- TOC entry 206 (class 1259 OID 21642)
-- Name: loan_id_seq; Type: SEQUENCE; Schema: public; Owner: ocr_admin
--

ALTER TABLE public.loan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 21644)
-- Name: member; Type: TABLE; Schema: public; Owner: ocr_admin
--

CREATE TABLE public.member (
                               id bigint NOT NULL,
                               cardnumber character varying(255),
                               email character varying(255)
);


ALTER TABLE public.member OWNER TO ocr_admin;

--
-- TOC entry 208 (class 1259 OID 21650)
-- Name: member_id_seq; Type: SEQUENCE; Schema: public; Owner: ocr_admin
--

ALTER TABLE public.member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2828 (class 2606 OID 21775)
-- Name: booking booking_pkey; Type: CONSTRAINT; Schema: public; Owner: ocr_admin
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (id);


--
-- TOC entry 2824 (class 2606 OID 21653)
-- Name: loan loan_pkey; Type: CONSTRAINT; Schema: public; Owner: ocr_admin
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT loan_pkey PRIMARY KEY (id);


--
-- TOC entry 2826 (class 2606 OID 21655)
-- Name: member member_pkey; Type: CONSTRAINT; Schema: public; Owner: ocr_admin
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_pkey PRIMARY KEY (id);


--
-- TOC entry 2830 (class 2606 OID 21776)
-- Name: booking fkr200vemsolh30s8wvtold760v; Type: FK CONSTRAINT; Schema: public; Owner: ocr_admin
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkr200vemsolh30s8wvtold760v FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- TOC entry 2829 (class 2606 OID 21656)
-- Name: loan fkskvlv9lnj3plivn0grmqf950f; Type: FK CONSTRAINT; Schema: public; Owner: ocr_admin
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT fkskvlv9lnj3plivn0grmqf950f FOREIGN KEY (member_id) REFERENCES public.member(id);


-- Completed on 2021-02-09 10:28:45 CET

