--
-- PostgreSQL database dump
--

-- Dumped from database version 12.5 (Ubuntu 12.5-1.pgdg20.04+1)
-- Dumped by pg_dump version 13.1 (Ubuntu 13.1-1.pgdg20.04+1)

-- Started on 2020-11-19 19:23:39 CET

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 207 (class 1259 OID 20916)
-- Name: batch_job_execution_seq; Type: SEQUENCE; Schema: public; Owner: ocr_admin
--

CREATE SEQUENCE public.batch_job_execution_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.batch_job_execution_seq OWNER TO ocr_admin;

--
-- TOC entry 208 (class 1259 OID 20918)
-- Name: batch_job_seq; Type: SEQUENCE; Schema: public; Owner: ocr_admin
--

CREATE SEQUENCE public.batch_job_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.batch_job_seq OWNER TO ocr_admin;

--
-- TOC entry 206 (class 1259 OID 20914)
-- Name: batch_step_execution_seq; Type: SEQUENCE; Schema: public; Owner: ocr_admin
--

CREATE SEQUENCE public.batch_step_execution_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.batch_step_execution_seq OWNER TO ocr_admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 203 (class 1259 OID 20824)
-- Name: loan; Type: TABLE; Schema: public; Owner: ocr_admin
--

CREATE TABLE public.loan (
    id bigint NOT NULL,
    book_back_date date,
    label character varying(255),
    refresh_ending_counter integer NOT NULL,
    starting_date date,
    title character varying(255),
    member_id bigint
);


ALTER TABLE public.loan OWNER TO ocr_admin;

--
-- TOC entry 202 (class 1259 OID 20822)
-- Name: loan_id_seq; Type: SEQUENCE; Schema: public; Owner: ocr_admin
--

ALTER TABLE public.loan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 20834)
-- Name: member; Type: TABLE; Schema: public; Owner: ocr_admin
--

CREATE TABLE public.member (
    id bigint NOT NULL,
    cardnumber character varying(255),
    email character varying(255)
);


ALTER TABLE public.member OWNER TO ocr_admin;

--
-- TOC entry 204 (class 1259 OID 20832)
-- Name: member_id_seq; Type: SEQUENCE; Schema: public; Owner: ocr_admin
--

ALTER TABLE public.member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2818 (class 2606 OID 20831)
-- Name: loan loan_pkey; Type: CONSTRAINT; Schema: public; Owner: ocr_admin
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT loan_pkey PRIMARY KEY (id);


--
-- TOC entry 2820 (class 2606 OID 20841)
-- Name: member member_pkey; Type: CONSTRAINT; Schema: public; Owner: ocr_admin
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_pkey PRIMARY KEY (id);


--
-- TOC entry 2821 (class 2606 OID 20842)
-- Name: loan fkskvlv9lnj3plivn0grmqf950f; Type: FK CONSTRAINT; Schema: public; Owner: ocr_admin
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT fkskvlv9lnj3plivn0grmqf950f FOREIGN KEY (member_id) REFERENCES public.member(id);


-- Completed on 2020-11-19 19:23:40 CET

--
-- PostgreSQL database dump complete
--

