--
-- PostgreSQL database dump
--

-- Dumped from database version 12.5 (Ubuntu 12.5-1.pgdg20.04+1)
-- Dumped by pg_dump version 13.1 (Ubuntu 13.1-1.pgdg20.04+1)

-- Started on 2021-02-09 10:36:33 CET

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3007 (class 1262 OID 21522)
-- Name: ocr_bibliotheque; Type: DATABASE; Schema: -; Owner: ocr_admin
--

CREATE DATABASE testbibliotheque WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.UTF-8';


ALTER DATABASE testbibliotheque OWNER TO ocr_admin;

\connect testbibliotheque

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 21661)
-- Name: author; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.author (
                               id_author bigint NOT NULL,
                               firstname character varying(255),
                               lastname character varying(255)
);


ALTER TABLE public.author OWNER TO ocr_admin;

--
-- TOC entry 203 (class 1259 OID 21667)
-- Name: author_id_author_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.author ALTER COLUMN id_author ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.author_id_author_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 204 (class 1259 OID 21669)
-- Name: book; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book (
                             idbook bigint NOT NULL,
                             category character varying(255),
                             description text,
                             image character varying(255),
                             isbn character varying(255),
                             title character varying(255),
                             year integer NOT NULL,
                             publisher_id_publisher bigint
);


ALTER TABLE public.book OWNER TO ocr_admin;

--
-- TOC entry 205 (class 1259 OID 21675)
-- Name: book_author; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book_author (
                                    idbook bigint NOT NULL,
                                    id_author bigint NOT NULL
);


ALTER TABLE public.book_author OWNER TO ocr_admin;

--
-- TOC entry 206 (class 1259 OID 21678)
-- Name: book_idbook_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.book ALTER COLUMN idbook ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_idbook_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 21680)
-- Name: book_topics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book_topics (
                                    idbook bigint NOT NULL,
                                    id_topics bigint NOT NULL
);


ALTER TABLE public.book_topics OWNER TO ocr_admin;

--
-- TOC entry 208 (class 1259 OID 21683)
-- Name: library; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.library (
                                id_library bigint NOT NULL,
                                address character varying(255),
                                library_name character varying(255),
                                opening_hours character varying(255)
);


ALTER TABLE public.library OWNER TO ocr_admin;

--
-- TOC entry 209 (class 1259 OID 21689)
-- Name: library_id_library_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.library ALTER COLUMN id_library ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.library_id_library_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 21691)
-- Name: publisher; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.publisher (
                                  id_publisher bigint NOT NULL,
                                  name character varying(255)
);


ALTER TABLE public.publisher OWNER TO ocr_admin;

--
-- TOC entry 211 (class 1259 OID 21694)
-- Name: publisher_id_publisher_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.publisher ALTER COLUMN id_publisher ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.publisher_id_publisher_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 21696)
-- Name: stock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stock (
                              label character varying(255),
                              pillar character varying(255),
                              shelf character varying(255),
                              wings character varying(255),
                              idbook bigint NOT NULL,
                              id_library bigint NOT NULL
);


ALTER TABLE public.stock OWNER TO ocr_admin;

--
-- TOC entry 213 (class 1259 OID 21702)
-- Name: topic; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.topic (
                              id_topic bigint NOT NULL,
                              keyword character varying(255)
);


ALTER TABLE public.topic OWNER TO ocr_admin;

--
-- TOC entry 214 (class 1259 OID 21705)
-- Name: topic_id_topic_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.topic ALTER COLUMN id_topic ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topic_id_topic_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2844 (class 2606 OID 21708)
-- Name: author author_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.author
    ADD CONSTRAINT author_pkey PRIMARY KEY (id_author);


--
-- TOC entry 2852 (class 2606 OID 21710)
-- Name: book_author book_author_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_author
    ADD CONSTRAINT book_author_pkey PRIMARY KEY (idbook, id_author);


--
-- TOC entry 2848 (class 2606 OID 21712)
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (idbook);


--
-- TOC entry 2854 (class 2606 OID 21714)
-- Name: book_topics book_topics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_topics
    ADD CONSTRAINT book_topics_pkey PRIMARY KEY (idbook, id_topics);


--
-- TOC entry 2846 (class 2606 OID 21716)
-- Name: author firstname_lastname; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.author
    ADD CONSTRAINT firstname_lastname UNIQUE (firstname, lastname);


--
-- TOC entry 2856 (class 2606 OID 21718)
-- Name: library library_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.library
    ADD CONSTRAINT library_pkey PRIMARY KEY (id_library);


--
-- TOC entry 2860 (class 2606 OID 21720)
-- Name: publisher publisher_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.publisher
    ADD CONSTRAINT publisher_pkey PRIMARY KEY (id_publisher);


--
-- TOC entry 2864 (class 2606 OID 21722)
-- Name: stock stock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock
    ADD CONSTRAINT stock_pkey PRIMARY KEY (idbook, id_library);


--
-- TOC entry 2866 (class 2606 OID 21724)
-- Name: topic topic_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT topic_pkey PRIMARY KEY (id_topic);


--
-- TOC entry 2858 (class 2606 OID 21726)
-- Name: library uk_6jj7g870fs607y0b7s5avdf7y; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.library
    ADD CONSTRAINT uk_6jj7g870fs607y0b7s5avdf7y UNIQUE (library_name);


--
-- TOC entry 2850 (class 2606 OID 21728)
-- Name: book uk_ehpdfjpu1jm3hijhj4mm0hx9h; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT uk_ehpdfjpu1jm3hijhj4mm0hx9h UNIQUE (isbn);


--
-- TOC entry 2862 (class 2606 OID 21730)
-- Name: publisher uk_h9trv4xhmh6s68vbw9ba6to70; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.publisher
    ADD CONSTRAINT uk_h9trv4xhmh6s68vbw9ba6to70 UNIQUE (name);


--
-- TOC entry 2868 (class 2606 OID 21732)
-- Name: topic uk_ibwo43iqc542j8hn715ofq3sh; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT uk_ibwo43iqc542j8hn715ofq3sh UNIQUE (keyword);


--
-- TOC entry 2874 (class 2606 OID 21733)
-- Name: stock fk26sepx4x9ynotm9733s5b57ff; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock
    ADD CONSTRAINT fk26sepx4x9ynotm9733s5b57ff FOREIGN KEY (idbook) REFERENCES public.book(idbook);


--
-- TOC entry 2870 (class 2606 OID 21738)
-- Name: book_author fk30k230rd6eua2ydag0hnpjv3j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_author
    ADD CONSTRAINT fk30k230rd6eua2ydag0hnpjv3j FOREIGN KEY (idbook) REFERENCES public.book(idbook);


--
-- TOC entry 2875 (class 2606 OID 21743)
-- Name: stock fk3xp49y8ljx14ix0et4mofbaib; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock
    ADD CONSTRAINT fk3xp49y8ljx14ix0et4mofbaib FOREIGN KEY (id_library) REFERENCES public.library(id_library);


--
-- TOC entry 2872 (class 2606 OID 21748)
-- Name: book_topics fkg9cse9id0xt0syl9ddmif7fwj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_topics
    ADD CONSTRAINT fkg9cse9id0xt0syl9ddmif7fwj FOREIGN KEY (idbook) REFERENCES public.book(idbook);


--
-- TOC entry 2873 (class 2606 OID 21753)
-- Name: book_topics fkiextn9j6c1wll1badhr7gy7v7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_topics
    ADD CONSTRAINT fkiextn9j6c1wll1badhr7gy7v7 FOREIGN KEY (id_topics) REFERENCES public.topic(id_topic);


--
-- TOC entry 2869 (class 2606 OID 21758)
-- Name: book fkj7qlls84ugf4jcrbmew67yscv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT fkj7qlls84ugf4jcrbmew67yscv FOREIGN KEY (publisher_id_publisher) REFERENCES public.publisher(id_publisher);


--
-- TOC entry 2871 (class 2606 OID 21763)
-- Name: book_author fkpwgpe60vfxwp9hdv10e7f186m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_author
    ADD CONSTRAINT fkpwgpe60vfxwp9hdv10e7f186m FOREIGN KEY (id_author) REFERENCES public.author(id_author);


-- Completed on 2021-02-09 10:36:33 CET


